# Site wide configuration

title:            Chirishman PowerShell
locale:           en_US
url:              http://blog.chiriserv.org

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

# Site owner
owner:
  name: Chirishman
  avatar: bio.png
  bio: "Sysadmin with an interest in PowerShell, automation, SBCs, and Datavis."
  email:
  #disqus-shortname: ramblingcookiemonster
  twitter: the_chirishman
  #google:
    #analytics: UA-61008962-1
  bing-verify:
  github: chirishman
  stackoverflow: 3661504/chirishman
  #linkedin: wframe
  #technet: https://social.technet.microsoft.com/profile/cookie.monster
  #wordpress: https://ramblingcookiemonster.wordpress.com
  rss: feed.xml
  #Github repos in sidebar - match them up to the repository name...
  githubrepos: [
          "ADAuth",
          "Keystore",
          "PowerArchiver",
          "Powershell-SlackBot",
          "StoredPSCredential"]

#UA-61008962-1

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
